runtime: python39

entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  NATION_SLUG: 'biitechdev'
  OAUTH_ID: '51c968804b080822ff338439ac7446338c232a438fc8fdca8fbadf33bdcd7cdc'
  OAUTH_SECRET: '73c118af02175e7a0858223655ab6dd8dc92189fc668220c22f57f96b6da69c7'
  REDIRECT_URI: 'http://biitechdev.nationbuilder.com/complete/nationbuilder/'
  SESSION_TOKEN: '5011babad2269d8d497c72aee5a93a06a069a39ee7624ac173db4a653cda98bc'
